"""Added crossed out to Entry

Revision ID: 8034a124960b
Revises: ab8ac8acefc1
Create Date: 2021-10-07 14:17:58.175154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8034a124960b'
down_revision = 'ab8ac8acefc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('crossedOut', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'crossedOut')
    # ### end Alembic commands ###
