"""users table

Revision ID: 8e5f64c2fbe7
Revises: 8034a124960b
Create Date: 2021-10-17 17:40:02.602504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5f64c2fbe7'
down_revision = '8034a124960b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('userOfTodo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'user', ['userOfTodo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'userOfTodo')
    op.drop_table('user')
    # ### end Alembic commands ###
