"""Added a column in Todo

Revision ID: ab8ac8acefc1
Revises: 
Create Date: 2021-09-28 09:36:49.026485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8ac8acefc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_dateOfTodo', table_name='todo')
    op.drop_table('todo')
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entryContent', sa.VARCHAR(length=300), nullable=True),
    sa.Column('referenceTodo', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['referenceTodo'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dateOfTodo', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todo_dateOfTodo', 'todo', ['dateOfTodo'], unique=False)
    # ### end Alembic commands ###
